services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - .env
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - mongo