services:
  proxy:
    build: 
      context: projects/proxy
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    depends_on:
      - web
  web:
    build:
      context: projects/web
    restart: always
    env_file:
      - .env
    volumes:
      - /data/next-swim-event:/data
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
#    ports:
#      - 27017:27017
    env_file:
      - .env
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    env_file:
#      - .env
#    depends_on:
#      - mongo